/* Generated by tools/genfuncs.py from src/aatext.funcs - do not edit. */
#ifndef CLIB_AATEXT_PROTOS_H
#define CLIB_AATEXT_PROTOS_H

/*
 * The bullet.library API of aatext.library. The FreeType API
 * is declared by the FreeType headers themselves.
 */

#include <exec/types.h>
#include <utility/tagitem.h>
#include <diskfont/glyph.h>

struct GlyphEngine * OpenEngine(void);
void CloseEngine(struct GlyphEngine *ge);
ULONG SetInfoA(struct GlyphEngine *ge, struct TagItem *tags);
ULONG ObtainInfoA(struct GlyphEngine *ge, struct TagItem *tags);
ULONG ReleaseInfoA(struct GlyphEngine *ge, struct TagItem *tags);

#endif
