/* Generated by tools/genfuncs.py from src/aatext.funcs - do not edit. */
#ifndef PROTO_AATEXT_H
#define PROTO_AATEXT_H

#include <exec/types.h>
#include <libraries/aatext.h>
#include <ft2build.h>
#include FT_FREETYPE_H
#include FT_GLYPH_H
#include FT_IMAGE_H
#include FT_SYSTEM_H
#include FT_TYPES_H
#include FT_CACHE_H
#include FT_TRIGONOMETRY_H
#include FT_MODULE_H
#include FT_LIST_H
#include FT_TRUETYPE_TABLES_H
#include FT_SFNT_NAMES_H
#include FT_COLOR_H
#include FT_OUTLINE_H
#include FT_STROKER_H
#include FT_LCD_FILTER_H
#include FT_MULTIPLE_MASTERS_H
#include FT_SYNTHESIS_H
#include FT_BBOX_H
#include FT_BITMAP_H
#include FT_ADVANCES_H
#include FT_GZIP_H
#include FT_FONT_FORMATS_H
#include FT_DRIVER_H
#include FT_SIZES_H
#include FT_RENDER_H
#include FT_PARAMETER_TAGS_H

#ifndef __NOLIBBASE__
extern struct Library *AATextBase;
#endif

#include <clib/aatext_protos.h>

#if defined(__GNUC__) && !defined(AATEXT_NO_INLINE)
#include <inline/aatext.h>
#endif

#endif
