/* Generated by tools/genfuncs.py from src/aatext.funcs - do not edit. */
#ifndef _INLINE_AATEXT_H
#define _INLINE_AATEXT_H

/*
 * Calls into aatext.library for gcc. Include <proto/aatext.h>,
 * which includes the FreeType headers first: these macros must come
 * after the FreeType prototypes they replace.
 *
 * The FreeType functions take their arguments on the stack; a call
 * jumps through the library vector like a normal C function call.
 */

#ifndef __INLINE_MACROS_H
#include <inline/macros.h>
#endif

#ifndef AATEXT_BASE_NAME
#define AATEXT_BASE_NAME AATextBase
#endif

#define AATEXT_LVO_(off) ((void *)((char *)(AATEXT_BASE_NAME) - (off)))

#define OpenEngine() \
	LP0(30, struct GlyphEngine *, OpenEngine, \
	struct Library *, AATEXT_BASE_NAME)

#define CloseEngine(p1) \
	LP1NR(36, CloseEngine, struct GlyphEngine *, p1, a0, \
	struct Library *, AATEXT_BASE_NAME)

#define SetInfoA(p1, p2) \
	LP2(42, ULONG, SetInfoA, struct GlyphEngine *, p1, a0, struct TagItem *, p2, a1, \
	struct Library *, AATEXT_BASE_NAME)

#define ObtainInfoA(p1, p2) \
	LP2(48, ULONG, ObtainInfoA, struct GlyphEngine *, p1, a0, struct TagItem *, p2, a1, \
	struct Library *, AATEXT_BASE_NAME)

#define ReleaseInfoA(p1, p2) \
	LP2(54, ULONG, ReleaseInfoA, struct GlyphEngine *, p1, a0, struct TagItem *, p2, a1, \
	struct Library *, AATEXT_BASE_NAME)

#define FT_Init_FreeType(p1) \
	(((FT_Error (*)(FT_Library *))AATEXT_LVO_(90))((p1)))

#define FT_Done_FreeType(p1) \
	(((FT_Error (*)(FT_Library))AATEXT_LVO_(96))((p1)))

#define FT_Library_Version(p1, p2, p3, p4) \
	(((void (*)(FT_Library, FT_Int *, FT_Int *, FT_Int *))AATEXT_LVO_(102))((p1), (p2), (p3), (p4)))

#define FT_New_Face(p1, p2, p3, p4) \
	(((FT_Error (*)(FT_Library, const char *, FT_Long, FT_Face *))AATEXT_LVO_(108))((p1), (p2), (p3), (p4)))

#define FT_Done_Face(p1) \
	(((FT_Error (*)(FT_Face))AATEXT_LVO_(114))((p1)))

#define FT_New_Memory_Face(p1, p2, p3, p4, p5) \
	(((FT_Error (*)(FT_Library, const FT_Byte *, FT_Long, FT_Long, FT_Face *))AATEXT_LVO_(120))((p1), (p2), (p3), (p4), (p5)))

#define FT_Open_Face(p1, p2, p3, p4) \
	(((FT_Error (*)(FT_Library, const FT_Open_Args *, FT_Long, FT_Face *))AATEXT_LVO_(126))((p1), (p2), (p3), (p4)))

#define FT_Attach_File(p1, p2) \
	(((FT_Error (*)(FT_Face, const char *))AATEXT_LVO_(132))((p1), (p2)))

#define FT_Attach_Stream(p1, p2) \
	(((FT_Error (*)(FT_Face, const FT_Open_Args *))AATEXT_LVO_(138))((p1), (p2)))

#define FT_Set_Char_Size(p1, p2, p3, p4, p5) \
	(((FT_Error (*)(FT_Face, FT_F26Dot6, FT_F26Dot6, FT_UInt, FT_UInt))AATEXT_LVO_(144))((p1), (p2), (p3), (p4), (p5)))

#define FT_Set_Pixel_Sizes(p1, p2, p3) \
	(((FT_Error (*)(FT_Face, FT_UInt, FT_UInt))AATEXT_LVO_(150))((p1), (p2), (p3)))

#define FT_Set_Transform(p1, p2, p3) \
	(((void (*)(FT_Face, FT_Matrix *, FT_Vector *))AATEXT_LVO_(156))((p1), (p2), (p3)))

#define FT_Load_Glyph(p1, p2, p3) \
	(((FT_Error (*)(FT_Face, FT_UInt, FT_Int32))AATEXT_LVO_(162))((p1), (p2), (p3)))

#define FT_Get_Char_Index(p1, p2) \
	(((FT_UInt (*)(FT_Face, FT_ULong))AATEXT_LVO_(168))((p1), (p2)))

#define FT_Get_Name_Index(p1, p2) \
	(((FT_UInt (*)(FT_Face, const FT_String *))AATEXT_LVO_(174))((p1), (p2)))

#define FT_Load_Char(p1, p2, p3) \
	(((FT_Error (*)(FT_Face, FT_ULong, FT_Int32))AATEXT_LVO_(180))((p1), (p2), (p3)))

#define FT_Render_Glyph(p1, p2) \
	(((FT_Error (*)(FT_GlyphSlot, FT_Render_Mode))AATEXT_LVO_(186))((p1), (p2)))

#define FT_Get_Kerning(p1, p2, p3, p4, p5) \
	(((FT_Error (*)(FT_Face, FT_UInt, FT_UInt, FT_UInt, FT_Vector *))AATEXT_LVO_(192))((p1), (p2), (p3), (p4), (p5)))

#define FT_Get_Glyph_Name(p1, p2, p3, p4) \
	(((FT_Error (*)(FT_Face, FT_UInt, FT_Pointer, FT_UInt))AATEXT_LVO_(198))((p1), (p2), (p3), (p4)))

#define FT_Get_Postscript_Name(p1) \
	(((const char * (*)(FT_Face))AATEXT_LVO_(204))((p1)))

#define FT_Select_Charmap(p1, p2) \
	(((FT_Error (*)(FT_Face, FT_Encoding))AATEXT_LVO_(210))((p1), (p2)))

#define FT_Set_Charmap(p1, p2) \
	(((FT_Error (*)(FT_Face, FT_CharMap))AATEXT_LVO_(216))((p1), (p2)))

#define FT_Get_First_Char(p1, p2) \
	(((FT_ULong (*)(FT_Face, FT_UInt *))AATEXT_LVO_(222))((p1), (p2)))

#define FT_Get_Next_Char(p1, p2, p3) \
	(((FT_ULong (*)(FT_Face, FT_ULong, FT_UInt *))AATEXT_LVO_(228))((p1), (p2), (p3)))

#define FT_Get_Glyph(p1, p2) \
	(((FT_Error (*)(FT_GlyphSlot, FT_Glyph *))AATEXT_LVO_(234))((p1), (p2)))

#define FT_Glyph_Copy(p1, p2) \
	(((FT_Error (*)(FT_Glyph, FT_Glyph *))AATEXT_LVO_(240))((p1), (p2)))

#define FT_Glyph_Transform(p1, p2, p3) \
	(((FT_Error (*)(FT_Glyph, const FT_Matrix*, const FT_Vector*))AATEXT_LVO_(246))((p1), (p2), (p3)))

#define FT_Glyph_Get_CBox(p1, p2, p3) \
	(((void (*)(FT_Glyph, FT_UInt, FT_BBox *))AATEXT_LVO_(252))((p1), (p2), (p3)))

#define FT_Glyph_To_Bitmap(p1, p2, p3, p4) \
	(((FT_Error (*)(FT_Glyph *, FT_Render_Mode, const FT_Vector *, FT_Bool))AATEXT_LVO_(258))((p1), (p2), (p3), (p4)))

#define FT_Done_Glyph(p1) \
	(((void (*)(FT_Glyph))AATEXT_LVO_(264))((p1)))

#define FT_New_Size(p1, p2) \
	(((FT_Error (*)(FT_Face, FT_Size *))AATEXT_LVO_(270))((p1), (p2)))

#define FT_Done_Size(p1) \
	(((FT_Error (*)(FT_Size))AATEXT_LVO_(276))((p1)))

#define FT_Activate_Size(p1) \
	(((FT_Error (*)(FT_Size))AATEXT_LVO_(282))((p1)))

#define FTC_Manager_New(p1, p2, p3, p4, p5, p6, p7) \
	(((FT_Error (*)(FT_Library, FT_UInt, FT_UInt, FT_ULong, FTC_Face_Requester, FT_Pointer, FTC_Manager *))AATEXT_LVO_(288))((p1), (p2), (p3), (p4), (p5), (p6), (p7)))

#define FTC_Manager_LookupFace(p1, p2, p3) \
	(((FT_Error (*)(FTC_Manager, FTC_FaceID, FT_Face *))AATEXT_LVO_(294))((p1), (p2), (p3)))

#define FTC_Manager_LookupSize(p1, p2, p3) \
	(((FT_Error (*)(FTC_Manager, FTC_Scaler, FT_Size *))AATEXT_LVO_(300))((p1), (p2), (p3)))

#define FTC_Node_Unref(p1, p2) \
	(((void (*)(FTC_Node, FTC_Manager))AATEXT_LVO_(306))((p1), (p2)))

#define FTC_ImageCache_New(p1, p2) \
	(((FT_Error (*)(FTC_Manager, FTC_ImageCache *))AATEXT_LVO_(312))((p1), (p2)))

#define FTC_ImageCache_Lookup(p1, p2, p3, p4, p5) \
	(((FT_Error (*)(FTC_ImageCache, FTC_ImageType, FT_UInt, FT_Glyph *, FTC_Node *))AATEXT_LVO_(318))((p1), (p2), (p3), (p4), (p5)))

#define FTC_SBitCache_New(p1, p2) \
	(((FT_Error (*)(FTC_Manager, FTC_SBitCache *))AATEXT_LVO_(324))((p1), (p2)))

#define FTC_SBitCache_Lookup(p1, p2, p3, p4, p5) \
	(((FT_Error (*)(FTC_SBitCache, FTC_ImageType, FT_UInt, FTC_SBit *, FTC_Node *))AATEXT_LVO_(330))((p1), (p2), (p3), (p4), (p5)))

#define FTC_Manager_Done(p1) \
	(((void (*)(FTC_Manager))AATEXT_LVO_(348))((p1)))

#define FTC_Manager_Reset(p1) \
	(((void (*)(FTC_Manager))AATEXT_LVO_(354))((p1)))

#define FTC_CMapCache_New(p1, p2) \
	(((FT_Error (*)(FTC_Manager, FTC_CMapCache *))AATEXT_LVO_(360))((p1), (p2)))

#define FTC_CMapCache_Lookup(p1, p2, p3, p4) \
	(((FT_UInt (*)(FTC_CMapCache, FTC_FaceID, FT_Int, FT_UInt32))AATEXT_LVO_(366))((p1), (p2), (p3), (p4)))

#define FT_MulDiv(p1, p2, p3) \
	(((FT_Long (*)(FT_Long, FT_Long, FT_Long))AATEXT_LVO_(390))((p1), (p2), (p3)))

#define FT_MulFix(p1, p2) \
	(((FT_Long (*)(FT_Long, FT_Long))AATEXT_LVO_(396))((p1), (p2)))

#define FT_DivFix(p1, p2) \
	(((FT_Long (*)(FT_Long, FT_Long))AATEXT_LVO_(402))((p1), (p2)))

#define FT_RoundFix(p1) \
	(((FT_Fixed (*)(FT_Fixed))AATEXT_LVO_(408))((p1)))

#define FT_CeilFix(p1) \
	(((FT_Fixed (*)(FT_Fixed))AATEXT_LVO_(414))((p1)))

#define FT_FloorFix(p1) \
	(((FT_Fixed (*)(FT_Fixed))AATEXT_LVO_(420))((p1)))

#define FT_Vector_Transform(p1, p2) \
	(((void (*)(FT_Vector *, const FT_Matrix *))AATEXT_LVO_(426))((p1), (p2)))

#define FT_Matrix_Multiply(p1, p2) \
	(((void (*)(const FT_Matrix *, FT_Matrix *))AATEXT_LVO_(432))((p1), (p2)))

#define FT_Matrix_Invert(p1) \
	(((FT_Error (*)(FT_Matrix *))AATEXT_LVO_(438))((p1)))

#define FT_Sin(p1) \
	(((FT_Fixed (*)(FT_Angle))AATEXT_LVO_(444))((p1)))

#define FT_Cos(p1) \
	(((FT_Fixed (*)(FT_Angle))AATEXT_LVO_(450))((p1)))

#define FT_Tan(p1) \
	(((FT_Fixed (*)(FT_Angle))AATEXT_LVO_(456))((p1)))

#define FT_Atan2(p1, p2) \
	(((FT_Angle (*)(FT_Fixed, FT_Fixed))AATEXT_LVO_(462))((p1), (p2)))

#define FT_Angle_Diff(p1, p2) \
	(((FT_Angle (*)(FT_Angle, FT_Angle))AATEXT_LVO_(468))((p1), (p2)))

#define FT_Vector_Unit(p1, p2) \
	(((void (*)(FT_Vector *, FT_Angle))AATEXT_LVO_(474))((p1), (p2)))

#define FT_Vector_Rotate(p1, p2) \
	(((void (*)(FT_Vector *, FT_Angle))AATEXT_LVO_(480))((p1), (p2)))

#define FT_Vector_Length(p1) \
	(((FT_Fixed (*)(FT_Vector *))AATEXT_LVO_(486))((p1)))

#define FT_Vector_Polarize(p1, p2, p3) \
	(((void (*)(FT_Vector *, FT_Fixed *, FT_Angle *))AATEXT_LVO_(492))((p1), (p2), (p3)))

#define FT_Vector_From_Polar(p1, p2, p3) \
	(((void (*)(FT_Vector *, FT_Fixed, FT_Angle))AATEXT_LVO_(498))((p1), (p2), (p3)))

#define FT_List_Add(p1, p2) \
	(((void (*)(FT_List, FT_ListNode))AATEXT_LVO_(504))((p1), (p2)))

#define FT_List_Insert(p1, p2) \
	(((void (*)(FT_List, FT_ListNode))AATEXT_LVO_(510))((p1), (p2)))

#define FT_List_Find(p1, p2) \
	(((FT_ListNode (*)(FT_List, void *))AATEXT_LVO_(516))((p1), (p2)))

#define FT_List_Remove(p1, p2) \
	(((void (*)(FT_List, FT_ListNode))AATEXT_LVO_(522))((p1), (p2)))

#define FT_List_Up(p1, p2) \
	(((void (*)(FT_List, FT_ListNode))AATEXT_LVO_(528))((p1), (p2)))

#define FT_List_Iterate(p1, p2, p3) \
	(((FT_Error (*)(FT_List, FT_List_Iterator, void *))AATEXT_LVO_(534))((p1), (p2), (p3)))

#define FT_List_Finalize(p1, p2, p3, p4) \
	(((void (*)(FT_List, FT_List_Destructor, FT_Memory, void *))AATEXT_LVO_(540))((p1), (p2), (p3), (p4)))

#define FT_Outline_New(p1, p2, p3, p4) \
	(((FT_Error (*)(FT_Library, FT_UInt, FT_Int, FT_Outline *))AATEXT_LVO_(546))((p1), (p2), (p3), (p4)))

#define FT_Outline_Done(p1, p2) \
	(((FT_Error (*)(FT_Library, FT_Outline *))AATEXT_LVO_(558))((p1), (p2)))

#define FT_Outline_Copy(p1, p2) \
	(((FT_Error (*)(const FT_Outline *, FT_Outline *))AATEXT_LVO_(570))((p1), (p2)))

#define FT_Outline_Translate(p1, p2, p3) \
	(((void (*)(const FT_Outline *, FT_Pos, FT_Pos))AATEXT_LVO_(576))((p1), (p2), (p3)))

#define FT_Outline_Transform(p1, p2) \
	(((void (*)(const FT_Outline *, const FT_Matrix *))AATEXT_LVO_(582))((p1), (p2)))

#define FT_Outline_Reverse(p1) \
	(((void (*)(FT_Outline *))AATEXT_LVO_(588))((p1)))

#define FT_Outline_Check(p1) \
	(((FT_Error (*)(FT_Outline *))AATEXT_LVO_(594))((p1)))

#define FT_Outline_Get_CBox(p1, p2) \
	(((void (*)(const FT_Outline *, FT_BBox *))AATEXT_LVO_(600))((p1), (p2)))

#define FT_Outline_Get_BBox(p1, p2) \
	(((FT_Error (*)(FT_Outline *, FT_BBox *))AATEXT_LVO_(606))((p1), (p2)))

#define FT_Outline_Get_Bitmap(p1, p2, p3) \
	(((FT_Error (*)(FT_Library, FT_Outline *, const FT_Bitmap *))AATEXT_LVO_(612))((p1), (p2), (p3)))

#define FT_Outline_Render(p1, p2, p3) \
	(((FT_Error (*)(FT_Library, FT_Outline *, FT_Raster_Params *))AATEXT_LVO_(618))((p1), (p2), (p3)))

#define FT_Outline_Decompose(p1, p2, p3) \
	(((FT_Error (*)(FT_Outline *, const FT_Outline_Funcs *, void *))AATEXT_LVO_(624))((p1), (p2), (p3)))

#define FT_Add_Module(p1, p2) \
	(((FT_Error (*)(FT_Library, const FT_Module_Class *))AATEXT_LVO_(630))((p1), (p2)))

#define FT_Get_Module(p1, p2) \
	(((FT_Module (*)(FT_Library, const char *))AATEXT_LVO_(636))((p1), (p2)))

#define FT_Remove_Module(p1, p2) \
	(((FT_Error (*)(FT_Library, FT_Module))AATEXT_LVO_(642))((p1), (p2)))

#define FT_New_Library(p1, p2) \
	(((FT_Error (*)(FT_Memory, FT_Library *))AATEXT_LVO_(648))((p1), (p2)))

#define FT_Done_Library(p1) \
	(((FT_Error (*)(FT_Library))AATEXT_LVO_(654))((p1)))

#define FT_Set_Debug_Hook(p1, p2, p3) \
	(((void (*)(FT_Library, FT_UInt, FT_DebugHook_Func))AATEXT_LVO_(660))((p1), (p2), (p3)))

#define FT_Add_Default_Modules(p1) \
	(((void (*)(FT_Library))AATEXT_LVO_(666))((p1)))

#define FT_Get_Renderer(p1, p2) \
	(((FT_Renderer (*)(FT_Library, FT_Glyph_Format))AATEXT_LVO_(672))((p1), (p2)))

#define FT_Set_Renderer(p1, p2, p3, p4) \
	(((FT_Error (*)(FT_Library, FT_Renderer, FT_UInt, FT_Parameter *))AATEXT_LVO_(678))((p1), (p2), (p3), (p4)))

#define FT_Stream_OpenGzip(p1, p2) \
	(((FT_Error (*)(FT_Stream, FT_Stream))AATEXT_LVO_(684))((p1), (p2)))

#define FT_Get_Sfnt_Table(p1, p2) \
	(((void * (*)(FT_Face, FT_Sfnt_Tag))AATEXT_LVO_(690))((p1), (p2)))

#define FT_Get_Sfnt_Name(p1, p2, p3) \
	(((FT_Error (*)(FT_Face, FT_UInt, FT_SfntName *))AATEXT_LVO_(696))((p1), (p2), (p3)))

#define FT_Get_Sfnt_Name_Count(p1) \
	(((FT_UInt (*)(FT_Face))AATEXT_LVO_(702))((p1)))

#define FT_Load_Sfnt_Table(p1, p2, p3, p4, p5) \
	(((FT_Error (*)(FT_Face, FT_ULong, FT_Long, FT_Byte *, FT_ULong *))AATEXT_LVO_(708))((p1), (p2), (p3), (p4), (p5)))

#define FT_Select_Size(p1, p2) \
	(((FT_Error (*)(FT_Face, FT_Int))AATEXT_LVO_(714))((p1), (p2)))

#define FT_Get_X11_Font_Format(p1) \
	(((const char * (*)(FT_Face))AATEXT_LVO_(720))((p1)))

#define FT_Library_SetLcdFilter(p1, p2) \
	(((FT_Error (*)(FT_Library, FT_LcdFilter))AATEXT_LVO_(726))((p1), (p2)))

#define FT_Library_SetLcdFilterWeights(p1, p2) \
	(((FT_Error (*)(FT_Library, unsigned char *))AATEXT_LVO_(732))((p1), (p2)))

#define FT_Library_SetLcdGeometry(p1, p2) \
	(((FT_Error (*)(FT_Library, FT_Vector [3]))AATEXT_LVO_(738))((p1), (p2)))

#define FT_New_Glyph(p1, p2, p3) \
	(((FT_Error (*)(FT_Library, FT_Glyph_Format, FT_Glyph *))AATEXT_LVO_(744))((p1), (p2), (p3)))

#define FT_Get_Track_Kerning(p1, p2, p3, p4) \
	(((FT_Error (*)(FT_Face, FT_Fixed, FT_Int, FT_Fixed *))AATEXT_LVO_(750))((p1), (p2), (p3), (p4)))

#define FT_Get_Charmap_Index(p1) \
	(((FT_Int (*)(FT_CharMap))AATEXT_LVO_(756))((p1)))

#define FT_Get_Color_Glyph_Layer(p1, p2, p3, p4, p5) \
	(((FT_Bool (*)(FT_Face, FT_UInt, FT_UInt *, FT_UInt *, FT_LayerIterator*))AATEXT_LVO_(762))((p1), (p2), (p3), (p4), (p5)))

#define FT_GlyphSlot_Own_Bitmap(p1) \
	(((FT_Error (*)(FT_GlyphSlot))AATEXT_LVO_(768))((p1)))

#define FTC_Manager_RemoveFaceID(p1, p2) \
	(((void (*)(FTC_Manager, FTC_FaceID))AATEXT_LVO_(774))((p1), (p2)))

#define FTC_ImageCache_LookupScaler(p1, p2, p3, p4, p5, p6) \
	(((FT_Error (*)(FTC_ImageCache, FTC_Scaler, FT_ULong, FT_UInt, FT_Glyph *, FTC_Node *))AATEXT_LVO_(780))((p1), (p2), (p3), (p4), (p5), (p6)))

#define FTC_SBitCache_LookupScaler(p1, p2, p3, p4, p5, p6) \
	(((FT_Error (*)(FTC_SBitCache, FTC_Scaler, FT_ULong, FT_UInt, FTC_SBit *, FTC_Node *))AATEXT_LVO_(786))((p1), (p2), (p3), (p4), (p5), (p6)))

#define FT_Outline_EmboldenXY(p1, p2, p3) \
	(((FT_Error (*)(FT_Outline *, FT_Pos, FT_Pos))AATEXT_LVO_(792))((p1), (p2), (p3)))

#define FT_Get_Font_Format(p1) \
	(((const char * (*)(FT_Face))AATEXT_LVO_(798))((p1)))

#define FT_Property_Get(p1, p2, p3, p4) \
	(((FT_Error (*)(FT_Library, const FT_String *, const FT_String *, void *))AATEXT_LVO_(804))((p1), (p2), (p3), (p4)))

#define FT_Property_Set(p1, p2, p3, p4) \
	(((FT_Error (*)(FT_Library, const FT_String *, const FT_String *, const void *))AATEXT_LVO_(810))((p1), (p2), (p3), (p4)))

#define FT_Palette_Data_Get(p1, p2) \
	(((FT_Error (*)(FT_Face, FT_Palette_Data *))AATEXT_LVO_(816))((p1), (p2)))

#define FT_Palette_Select(p1, p2, p3) \
	(((FT_Error (*)(FT_Face, FT_UShort, FT_Color **))AATEXT_LVO_(822))((p1), (p2), (p3)))

#define FT_Bitmap_New(p1) \
	(((void (*)(FT_Bitmap *))AATEXT_LVO_(828))((p1)))

#define FT_Bitmap_Init(p1) \
	(((void (*)(FT_Bitmap *))AATEXT_LVO_(834))((p1)))

#define FT_Bitmap_Blend(p1, p2, p3, p4, p5, p6) \
	(((FT_Error (*)(FT_Library, const FT_Bitmap *, const FT_Vector, FT_Bitmap *, FT_Vector *, FT_Color))AATEXT_LVO_(840))((p1), (p2), (p3), (p4), (p5), (p6)))

#define FT_Bitmap_Convert(p1, p2, p3, p4) \
	(((FT_Error (*)(FT_Library, const FT_Bitmap *, FT_Bitmap *, FT_Int))AATEXT_LVO_(846))((p1), (p2), (p3), (p4)))

#define FT_Bitmap_Done(p1, p2) \
	(((FT_Error (*)(FT_Library, FT_Bitmap *))AATEXT_LVO_(852))((p1), (p2)))

#define FT_Bitmap_Embolden(p1, p2, p3, p4) \
	(((FT_Error (*)(FT_Library, FT_Bitmap *, FT_Pos, FT_Pos))AATEXT_LVO_(858))((p1), (p2), (p3), (p4)))

#define FT_Stroker_New(p1, p2) \
	(((FT_Error (*)(FT_Library, FT_Stroker *))AATEXT_LVO_(864))((p1), (p2)))

#define FT_Stroker_Set(p1, p2, p3, p4, p5) \
	(((void (*)(FT_Stroker, FT_Fixed, FT_Stroker_LineCap, FT_Stroker_LineJoin, FT_Fixed))AATEXT_LVO_(870))((p1), (p2), (p3), (p4), (p5)))

#define FT_Stroker_GetCounts(p1, p2, p3) \
	(((FT_Error (*)(FT_Stroker, FT_UInt *, FT_UInt *))AATEXT_LVO_(876))((p1), (p2), (p3)))

#define FT_Stroker_ParseOutline(p1, p2, p3) \
	(((FT_Error (*)(FT_Stroker, FT_Outline *, FT_Bool))AATEXT_LVO_(882))((p1), (p2), (p3)))

#define FT_Glyph_Stroke(p1, p2, p3) \
	(((FT_Error (*)(FT_Glyph *, FT_Stroker, FT_Bool))AATEXT_LVO_(888))((p1), (p2), (p3)))

#define FT_Glyph_StrokeBorder(p1, p2, p3, p4) \
	(((FT_Error (*)(FT_Glyph *, FT_Stroker, FT_Bool, FT_Bool))AATEXT_LVO_(894))((p1), (p2), (p3), (p4)))

#define FT_Stroker_Export(p1, p2) \
	(((void (*)(FT_Stroker, FT_Outline *))AATEXT_LVO_(900))((p1), (p2)))

#define FT_Stroker_Done(p1) \
	(((void (*)(FT_Stroker))AATEXT_LVO_(906))((p1)))

#define FT_Get_Advance(p1, p2, p3, p4) \
	(((FT_Error (*)(FT_Face, FT_UInt, FT_Int32, FT_Fixed *))AATEXT_LVO_(912))((p1), (p2), (p3), (p4)))

#define FT_Get_Advances(p1, p2, p3, p4, p5) \
	(((FT_Error (*)(FT_Face, FT_UInt, FT_UInt, FT_Int32, FT_Fixed *))AATEXT_LVO_(918))((p1), (p2), (p3), (p4), (p5)))

#define FT_Get_MM_Var(p1, p2) \
	(((FT_Error (*)(FT_Face, FT_MM_Var* *))AATEXT_LVO_(924))((p1), (p2)))

#define FT_Done_MM_Var(p1, p2) \
	(((FT_Error (*)(FT_Library, FT_MM_Var *))AATEXT_LVO_(930))((p1), (p2)))

#define FT_Set_Named_Instance(p1, p2) \
	(((FT_Error (*)(FT_Face, FT_UInt))AATEXT_LVO_(936))((p1), (p2)))

#define FT_Get_Default_Named_Instance(p1, p2) \
	(((FT_Error (*)(FT_Face, FT_UInt *))AATEXT_LVO_(942))((p1), (p2)))

#define FT_Get_Var_Design_Coordinates(p1, p2, p3) \
	(((FT_Error (*)(FT_Face, FT_UInt, FT_Fixed*))AATEXT_LVO_(948))((p1), (p2), (p3)))

#define FT_Set_Var_Design_Coordinates(p1, p2, p3) \
	(((FT_Error (*)(FT_Face, FT_UInt, FT_Fixed*))AATEXT_LVO_(954))((p1), (p2), (p3)))

#define FT_Face_GetCharVariantIndex(p1, p2, p3) \
	(((FT_UInt (*)(FT_Face, FT_ULong, FT_ULong))AATEXT_LVO_(960))((p1), (p2), (p3)))

#define FT_Reference_Library(p1) \
	(((FT_Error (*)(FT_Library))AATEXT_LVO_(966))((p1)))

#define FT_Reference_Face(p1) \
	(((FT_Error (*)(FT_Face))AATEXT_LVO_(972))((p1)))

#define FT_Set_Default_Properties(p1) \
	(((void (*)(FT_Library))AATEXT_LVO_(978))((p1)))

#define FT_Get_Transform(p1, p2, p3) \
	(((void (*)(FT_Face, FT_Matrix *, FT_Vector *))AATEXT_LVO_(984))((p1), (p2), (p3)))

#define FT_Sfnt_Table_Info(p1, p2, p3, p4) \
	(((FT_Error (*)(FT_Face, FT_UInt, FT_ULong *, FT_ULong *))AATEXT_LVO_(990))((p1), (p2), (p3), (p4)))

#define FT_Get_Var_Blend_Coordinates(p1, p2, p3) \
	(((FT_Error (*)(FT_Face, FT_UInt, FT_Fixed*))AATEXT_LVO_(996))((p1), (p2), (p3)))

#define FT_GlyphSlot_Embolden(p1) \
	(((void (*)(FT_GlyphSlot))AATEXT_LVO_(1002))((p1)))

#define FT_GlyphSlot_Oblique(p1) \
	(((void (*)(FT_GlyphSlot))AATEXT_LVO_(1008))((p1)))

#define FT_Palette_Set_Foreground_Color(p1, p2) \
	(((FT_Error (*)(FT_Face, FT_Color))AATEXT_LVO_(1014))((p1), (p2)))

#define FT_Get_Color_Glyph_Paint(p1, p2, p3, p4) \
	(((FT_Bool (*)(FT_Face, FT_UInt, FT_Color_Root_Transform, FT_OpaquePaint *))AATEXT_LVO_(1020))((p1), (p2), (p3), (p4)))

#define FT_Get_Color_Glyph_ClipBox(p1, p2, p3) \
	(((FT_Bool (*)(FT_Face, FT_UInt, FT_ClipBox *))AATEXT_LVO_(1026))((p1), (p2), (p3)))

#define FT_Get_Paint_Layers(p1, p2, p3) \
	(((FT_Bool (*)(FT_Face, FT_LayerIterator *, FT_OpaquePaint *))AATEXT_LVO_(1032))((p1), (p2), (p3)))

#define FT_Get_Colorline_Stops(p1, p2, p3) \
	(((FT_Bool (*)(FT_Face, FT_ColorStop *, FT_ColorStopIterator *))AATEXT_LVO_(1038))((p1), (p2), (p3)))

#define FT_Get_Paint(p1, p2, p3) \
	(((FT_Bool (*)(FT_Face, FT_OpaquePaint, FT_COLR_Paint *))AATEXT_LVO_(1044))((p1), (p2), (p3)))

#define FT_Request_Size(p1, p2) \
	(((FT_Error (*)(FT_Face, FT_Size_Request))AATEXT_LVO_(1050))((p1), (p2)))

#define FT_Outline_Embolden(p1, p2) \
	(((FT_Error (*)(FT_Outline *, FT_Pos))AATEXT_LVO_(1056))((p1), (p2)))

#define FT_Outline_Get_Orientation(p1) \
	(((FT_Orientation (*)(FT_Outline *))AATEXT_LVO_(1062))((p1)))

#define FT_Bitmap_Copy(p1, p2, p3) \
	(((FT_Error (*)(FT_Library, const FT_Bitmap *, FT_Bitmap *))AATEXT_LVO_(1068))((p1), (p2), (p3)))

#define FT_Error_String(p1) \
	(((const char * (*)(FT_Error))AATEXT_LVO_(1074))((p1)))

#define FT_Face_Properties(p1, p2, p3) \
	(((FT_Error (*)(FT_Face, FT_UInt, FT_Parameter *))AATEXT_LVO_(1080))((p1), (p2), (p3)))

#define FT_Get_FSType_Flags(p1) \
	(((FT_UShort (*)(FT_Face))AATEXT_LVO_(1086))((p1)))

#define FT_Set_Var_Blend_Coordinates(p1, p2, p3) \
	(((FT_Error (*)(FT_Face, FT_UInt, FT_Fixed*))AATEXT_LVO_(1092))((p1), (p2), (p3)))

#define FT_Get_Var_Axis_Flags(p1, p2, p3) \
	(((FT_Error (*)(FT_MM_Var *, FT_UInt, FT_UInt *))AATEXT_LVO_(1098))((p1), (p2), (p3)))

#define FT_Get_Sfnt_LangTag(p1, p2, p3) \
	(((FT_Error (*)(FT_Face, FT_UInt, FT_SfntLangTag *))AATEXT_LVO_(1104))((p1), (p2), (p3)))

#define FT_Get_CMap_Language_ID(p1) \
	(((FT_Long (*)(FT_CharMap))AATEXT_LVO_(1110))((p1)))

#define FT_Get_CMap_Format(p1) \
	(((FT_Long (*)(FT_CharMap))AATEXT_LVO_(1116))((p1)))

#endif
