#!/usr/bin/env python3
# Generate src/charsets.c: character code -> Unicode tables for the
# "charset" preference, from Python's own codecs (standard mappings).
# Usage: python3 -I tools/mkcharsets.py > src/charsets.c

# (pref keyword, Python codec, comment); order = AA_CHARSET_* in prefs.h
SETS = [
    ("latin1",   "iso8859_1",  "ISO-8859-1, Western European"),
    ("latin2",   "iso8859_2",  "ISO-8859-2, Central European"),
    ("latin3",   "iso8859_3",  "ISO-8859-3, South European"),
    ("latin4",   "iso8859_4",  "ISO-8859-4, North European"),
    ("latin5",   "iso8859_9",  "ISO-8859-9, Turkish"),
    ("latin9",   "iso8859_15", "ISO-8859-15, Western European with euro"),
    ("latin10",  "iso8859_16", "ISO-8859-16, South-Eastern European"),
    ("cp1250",   "cp1250",     "Windows-1250, Central European"),
    ("cyrillic", "iso8859_5",  "ISO-8859-5, Cyrillic"),
    ("koi8r",    "koi8_r",     "KOI8-R, Russian"),
]

print("/* Generated by tools/mkcharsets.py - do not edit. */")
print('#include "charsets.h"\n')
print("const char *const aa_CharsetNames[AA_NUM_CHARSETS] =\n{")
for name, _, _ in SETS:
    print('    "%s",' % name)
print("};\n")
print("/* codes 0x80-0xFF; 0 = not defined in the set */")
print("const UWORD aa_CharsetHigh[AA_NUM_CHARSETS][128] =\n{")
for name, codec, comment in SETS:
    print("    /* %s */\n    {" % comment)
    vals = []
    for c in range(128, 256):
        try:
            vals.append(ord(bytes([c]).decode(codec)))
        except UnicodeDecodeError:
            vals.append(0)
    for i in range(0, 128, 8):
        print("        " + ", ".join("0x%04X" % v for v in vals[i:i+8]) + ",")
    print("    },")
print("};")
