#ifndef AATEXT_CHARSETS_H
#define AATEXT_CHARSETS_H

#include <exec/types.h>

/*
 * 8-bit character sets for fonts without a code page of their own.
 * The order matches AA_CHARSET_* in prefs.h and the table in charsets.c
 * (generated by tools/mkcharsets.py). Codes below 0x80 are ASCII in all.
 */
#define AA_NUM_CHARSETS 10

extern const char *const aa_CharsetNames[AA_NUM_CHARSETS];
extern const UWORD aa_CharsetHigh[AA_NUM_CHARSETS][128];

/* Character code -> Unicode; codes the set leaves undefined map to c. */
static inline ULONG aa_CharsetToUnicode(UBYTE cs, UBYTE c)
{
    UWORD u;

    if (c < 0x80 || cs >= AA_NUM_CHARSETS)
        return c;
    u = aa_CharsetHigh[cs][c - 0x80];
    return u ? u : c;
}

/* The whole set as a 256-entry table (the ENV:ftcodepage format). */
static inline void aa_CharsetPage(UBYTE cs, UWORD *page)
{
    LONG i;

    for (i = 0; i < 256; i++)
        page[i] = aa_CharsetToUnicode(cs, i);
}

#endif
